version: '3.5'

networks:
  pongo-test-network:
    name: ${SERVICE_NETWORK_NAME}

services:
  postgres:
    image: postgres:${POSTGRES:-9.5}
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong_tests
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      interval: 5s
      retries: 10
      test:
      - CMD
      - pg_isready
      - --dbname=kong_tests
      - --username=kong
      timeout: 10s
    restart: on-failure
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}

  cassandra:
    image: cassandra:${CASSANDRA:-3.9}
    environment:
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: on-failure
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}

  redis:
    image: redis:${REDIS:-5.0.4}-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: on-failure
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}

  squid:
    image: sameersbn/squid:${SQUID:-3.5.27-2}
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
      - ./squid/passwords:/etc/squid/passwords
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD", "kill", "-0", "1"]
      timeout: 10s
    restart: on-failure
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}

  grpcbin:
    image: moul/grpcbin:latest
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD", "kill", "-0", "1"]
      timeout: 10s
    restart: on-failure
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}

  kong:
    image: ${KONG_TEST_IMAGE:-ignore_if_not_provided}
    environment:
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_PG_HOST=postgres
    networks:
      - ${NETWORK_NAME}
    volumes:
      - ${PONGO_WD}:/kong-plugin
